# Generated by Django 4.1.7 on 2023-05-06 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('accessibility_marker', models.BooleanField(default=True)),
                ('accessibility_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('accessibility_marker', models.BooleanField(default=True)),
                ('accessibility_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FileSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SectionKind',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SectionStatus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('login', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StatusData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='awwwapp.sectionstatus')),
            ],
        ),
        migrations.AddConstraint(
            model_name='sectionstatus',
            constraint=models.CheckConstraint(check=models.Q(('name__in', ['compiled', 'not compiled', 'compiled with warnings'])), name='status_name_in_set'),
        ),
        migrations.AddConstraint(
            model_name='sectionkind',
            constraint=models.CheckConstraint(check=models.Q(('name__in', ['procedure', 'comment', 'code', 'compiler directive', 'variable declaration', 'assembly code'])), name='kind_name_in_set'),
        ),
        migrations.AddField(
            model_name='filesection',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='awwwapp.file'),
        ),
        migrations.AddField(
            model_name='filesection',
            name='kind',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='awwwapp.sectionkind'),
        ),
        migrations.AddField(
            model_name='filesection',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='awwwapp.sectionstatus'),
        ),
        migrations.AddField(
            model_name='file',
            name='catalog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='awwwapp.catalog'),
        ),
        migrations.AddField(
            model_name='file',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='awwwapp.user'),
        ),
        migrations.AddField(
            model_name='catalog',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='awwwapp.user'),
        ),
        migrations.AddField(
            model_name='catalog',
            name='supercatalog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='awwwapp.catalog'),
        ),
    ]
