# Generated by Django 4.1.7 on 2023-05-08 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awwwapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='sectionstatus',
            name='status_name_in_set',
        ),
        migrations.AddConstraint(
            model_name='sectionstatus',
            constraint=models.CheckConstraint(check=models.Q(('name__in', ['Not tried', 'compiled', 'not compiled', 'compiled with warnings'])), name='status_name_in_set'),
        ),
    ]
