# Generated by Django 4.1.7 on 2023-06-15 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awwwapp', '0002_remove_sectionstatus_status_name_in_set_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionkind',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
